version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "Peperehobbits01"
    reviewers:
      - "Peperehobbits01"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore:"
    target-branch: "dev"