const PERMISSION_NOM = {
	CREATE_INSTANT_INVITE: "Créer des invitats",
	KICK_MEMBERS: "Exclure les membres",
	BAN_MEMBERS: "Bannir les membres",
	Administrator: "Administrateur",
	MANAGE_CHANNELS: "Gérer les canaux",
	MANAGE_GUILD: "Gérer le serveur",
	ADD_REACTIONS: "Ajouter des réactions",
	VIEW_AUDIT_LOG: "Voir l'historique d'audit",
	SCHEDULE_EVENTS: "Planifier des événements",
	PRIORITY_SPEAKER: "Orateur en priorité",
	STREAM: "Diffuser",
	VIEW_CHANNEL: "Voir le canal",
	SEND_MESSAGES: "Envoyer des messages",
	SEND_TTS_MESSAGES: "Envoyer des messages vocaux",
	MANAGE_MESSAGES: "Gérer les messages",
	EMBED_LINKS: "Inclure des liens",
	ATTACH_FILES: "Joindre des fichiers",
	READ_MESSAGE_HISTORY: "Lire l'historique des messages",
	MENTION_EVERYONE: "Mentionner tout le monde",
	USE_EXTERNAL_EMOJIS: "Utiliser des emojis externes",
	VIEW_GUILD_INSIGHTS: "Voir les statistiques du serveur",
	CONNECT: "Se connecter",
	SPEAK: "Parler",
	MUTE_MEMBERS: "Rendre les membres muets",
	DEAFEN_MEMBERS: "Rendre les membres inaudibles",
	MOVE_MEMBERS: "Déplacer les membres",
	USE_VAD: "Utiliser la détection d'activité",
	CHANGE_NICKNAME: "Changer de surnom",
	MANAGE_NICKNAMES: "Gérer les surnoms",
	MANAGE_ROLES: "Gérer les rôles",
	MANAGE_WEBHOOKS: "Gérer les webhooks",
	MANAGE_EMOJIS_AND_STICKERS: "Gérer les emojis et autocollants",
	MANAGE_EMOJIS: "Gérer les emojis",
	MANAGE_STICKERS: "Gérer les autocollants",
	USE_APPLICATION_COMMANDS: "Utiliser les commandes d'application",
	REQUEST_TO_SPEAK: "Demander à parler",
	USE_SOUNDS: "Utiliser des sons",
	MANAGE_THREADS: "Gérer les fils de discussion",
	USE_EXTERNAL_STICKERS: "Utiliser des autocollants externes",
	SEND_MESSAGES_IN_THREADS: "Envoyer des messages dans les fils de discussion",
	USE_EMBEDDED_ACTIVITIES: "Utiliser les activités intégrées",
	MODERATE_MEMBERS: "Moderer les membres",
	USE_VIDEOS: "Utiliser des vidéos",
	VIEW_CREATOR_MONETIZATION_ANALYTICS: "Voir les analyses de monétisation",
	USE_EXTERNAL_SOUNDS: "Utiliser des sons externes",
	CREATE_GUILD_EXPRESSIONS: "Créer des expressions de guilde",
	CREATE_EVENTS: "Créer des événements",
	CREATE_GUILD_TEMPLATE: "Créer un modèle de guilde",
	USE_EXTERNAL_APPS: "Utiliser des applications externes",
	START_EMBEDDED_ACTIVITIES: "Démarrer des activités intégrées",
	USE_IMPORT_EXPORT_PERMISSIONS: "Utiliser l'import/export de permissions",
	SEND_VOICE_CHANNEL_INTEGRATION_ACCESS: "Accès aux intégrations vocales",
	AUTOMOD_CREATE_PETITIONS: "Créer des pétitions",
	AUTOMOD_MODERATE_PETITIONS: "Modérer les pétitions",
	USE_EXTERNAL_SOUNDS_VIA_COMMANDS: "Utiliser des sons externes via commandes",
	USE_SOUNDTOUCH_FILTERS_AND_VIEWS: "Utiliser les filtres SoundTouch",
	USE_POLLS: "Utiliser des sondages",
	USE_EXTERNAL_SCRIPTS: "Utiliser des scripts externes"
};

module.exports = PERMISSION_NOM;
